-- Generated from the live catalog. Do not edit by hand.
-- Rebuilds an EMPTY database: no data, no function bodies.

CREATE TABLE IF NOT EXISTS public.api_usage (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid NOT NULL,\n  endpoint text NOT NULL,\n  called_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.arsenals (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  bowler_name text,\n  ball text,\n  created_by uuid DEFAULT gen_random_uuid(),\n  layout_system text,\n  layout_values jsonb,\n  group_id uuid,\n  coverstock text,\n  core_type text,\n  weight numeric,\n  rg numeric,\n  diff numeric,\n  int_diff numeric\n);
CREATE TABLE IF NOT EXISTS public.bags (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_by uuid,\n  bowler_name text NOT NULL,\n  name text NOT NULL,\n  bag_type text DEFAULT 'league'::text NOT NULL,\n  ball_limit integer,\n  includes_plastic boolean DEFAULT false NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.ball_bags (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_by uuid,\n  bowler_name text NOT NULL,\n  ball text NOT NULL,\n  bag_id uuid NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.ball_confirmations (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  submission_id uuid NOT NULL,\n  confirmed_by uuid,\n  vote text DEFAULT 'approve'::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.ball_groups (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_by uuid,\n  bowler_name text NOT NULL,\n  name text NOT NULL,\n  sort_order integer DEFAULT 0 NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.ball_submissions (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  submitted_by uuid,\n  ball_key text NOT NULL,\n  ball_name text NOT NULL,\n  brand text,\n  coverstock text,\n  core_type text,\n  weight numeric,\n  rg numeric,\n  diff numeric,\n  int_diff numeric,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  official boolean DEFAULT false NOT NULL,\n  source_note text,\n  weight_specs jsonb\n);
CREATE TABLE IF NOT EXISTS public.bowler_goals (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_by uuid,\n  bowler_name text NOT NULL,\n  goals jsonb DEFAULT '[]'::jsonb NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.bowler_names (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  created_by uuid DEFAULT gen_random_uuid(),\n  name text,\n  left_handed boolean DEFAULT false NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.bowler_profiles (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  created_by uuid,\n  bowler_name text NOT NULL,\n  left_handed boolean DEFAULT false NOT NULL,\n  two_handed boolean DEFAULT false NOT NULL,\n  home_centers text[] DEFAULT '{}'::text[] NOT NULL,\n  notes text,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  book_average numeric,\n  book_games integer,\n  book_season text,\n  book_average_as_of date,\n  is_coach boolean DEFAULT false NOT NULL,\n  aliases jsonb\n);
CREATE TABLE IF NOT EXISTS public.bowling_centers (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  here_id text,\n  name text NOT NULL,\n  address text,\n  city text,\n  state text,\n  postal_code text,\n  country text,\n  lat numeric,\n  lng numeric,\n  created_by uuid,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.coaching_notes (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  relationship_id uuid NOT NULL,\n  author_id uuid NOT NULL,\n  body text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.coaching_relationships (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  coach_id uuid NOT NULL,\n  bowler_id uuid NOT NULL,\n  requested_by uuid NOT NULL,\n  status text DEFAULT 'pending'::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  next_session date,\n  next_session_note text\n);
CREATE TABLE IF NOT EXISTS public.coaching_tasks (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  relationship_id uuid NOT NULL,\n  assigned_by uuid NOT NULL,\n  title text NOT NULL,\n  detail text,\n  metric_id text,\n  target numeric,\n  due_date date,\n  status text DEFAULT 'open'::text NOT NULL,\n  result numeric,\n  bowler_note text,\n  completed_at timestamp with time zone,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.drills (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid,\n  bowler_name text NOT NULL,\n  date date NOT NULL,\n  target text NOT NULL,\n  custom_target text,\n  ball text,\n  made integer DEFAULT 0 NOT NULL,\n  missed integer DEFAULT 0 NOT NULL,\n  notes text,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  custom_pins jsonb\n);
CREATE TABLE IF NOT EXISTS public.friendships (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  requester_id uuid NOT NULL,\n  addressee_id uuid NOT NULL,\n  status text DEFAULT 'pending'::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  responded_at timestamp with time zone\n);
CREATE TABLE IF NOT EXISTS public.hidden_leagues (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid,\n  league_id uuid,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.imported_scores (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  bowler_user_id uuid,\n  bowler_name text NOT NULL,\n  uploaded_by uuid NOT NULL,\n  team_id uuid,\n  league_id uuid,\n  date date NOT NULL,\n  imported_scores jsonb DEFAULT '[]'::jsonb NOT NULL,\n  corrected_scores jsonb,\n  status text DEFAULT 'pending'::text NOT NULL,\n  corrected_by uuid,\n  responded_at timestamp with time zone,\n  note text,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  imported_shots jsonb,\n  corrected_shots jsonb\n);
CREATE TABLE IF NOT EXISTS public.lane_patterns (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  team_id uuid,\n  league_id uuid,\n  date date NOT NULL,\n  lane text NOT NULL,\n  pattern_type text DEFAULT 'house'::text NOT NULL,\n  pattern_name text DEFAULT ''::text NOT NULL,\n  length text DEFAULT ''::text NOT NULL,\n  volume text DEFAULT ''::text NOT NULL,\n  ratio text DEFAULT ''::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.leagues (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  name text NOT NULL,\n  created_by uuid DEFAULT auth.uid(),\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  center_id uuid,\n  start_date date,\n  end_date date\n);
CREATE TABLE IF NOT EXISTS public.manual_scores (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid,\n  bowler_name text NOT NULL,\n  league_id uuid,\n  date date NOT NULL,\n  game integer NOT NULL,\n  score integer,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  ball text,\n  surface text\n);
CREATE TABLE IF NOT EXISTS public.matches (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  team_id uuid,\n  league_id uuid,\n  date date NOT NULL,\n  games jsonb DEFAULT '[null, null, null]'::jsonb NOT NULL,\n  series boolean,\n  opponent text DEFAULT ''::text NOT NULL,\n  handicap text DEFAULT ''::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.oil_patterns (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  name text NOT NULL,\n  series text,\n  length_feet numeric,\n  ratio text,\n  volume_ml numeric,\n  forward_ml numeric,\n  reverse_ml numeric,\n  verified boolean DEFAULT false NOT NULL,\n  source_note text,\n  created_by uuid,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  year integer\n);
CREATE TABLE IF NOT EXISTS public.pending_invites (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  team_id uuid NOT NULL,\n  invited_name text NOT NULL,\n  invited_email text,\n  lineup_position integer,\n  created_by uuid,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  accepted_at timestamp with time zone,\n  accepted_user_id uuid,\n  left_handed boolean DEFAULT false NOT NULL,\n  is_sub boolean DEFAULT false NOT NULL,\n  declined_at timestamp with time zone,\n  signup_code text,\n  code_expires_at timestamp with time zone\n);
CREATE TABLE IF NOT EXISTS public.profiles (\n  id uuid NOT NULL,\n  display_name text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.sessions (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid NOT NULL,\n  team_id uuid,\n  league_id uuid,\n  bowler_name text DEFAULT ''::text NOT NULL,\n  date date NOT NULL,\n  scores integer[] DEFAULT '{}'::integer[] NOT NULL,\n  total integer,\n  average integer,\n  shot_count integer DEFAULT 0 NOT NULL,\n  strikes integer DEFAULT 0 NOT NULL,\n  weak_tens integer DEFAULT 0 NOT NULL,\n  ringing_tens integer DEFAULT 0 NOT NULL,\n  ten_pin_leaves integer DEFAULT 0 NOT NULL,\n  single_pin_leaves integer DEFAULT 0 NOT NULL,\n  single_pin_spares integer DEFAULT 0 NOT NULL,\n  spare_attempts integer DEFAULT 0 NOT NULL,\n  spares_made integer DEFAULT 0 NOT NULL,\n  splits integer DEFAULT 0 NOT NULL,\n  splits_converted integer DEFAULT 0 NOT NULL,\n  balls_used jsonb DEFAULT '[]'::jsonb NOT NULL,\n  misses jsonb DEFAULT '[]'::jsonb NOT NULL,\n  releases jsonb DEFAULT '[]'::jsonb NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  poker_quarter jsonb DEFAULT '[0, 0, 0]'::jsonb NOT NULL,\n  poker_dollar jsonb DEFAULT '[0, 0, 0]'::jsonb NOT NULL,\n  three_six_nine_winnings numeric DEFAULT 0 NOT NULL,\n  jackpot_winnings numeric DEFAULT 0 NOT NULL,\n  high_game_winnings numeric[] DEFAULT '{0,0,0}'::numeric[] NOT NULL,\n  high_game_cost numeric[] DEFAULT '{0,0,0}'::numeric[] NOT NULL,\n  poker_quarter_cost numeric[] DEFAULT '{0,0,0}'::numeric[] NOT NULL,\n  poker_dollar_cost numeric[] DEFAULT '{0,0,0}'::numeric[] NOT NULL,\n  three_six_nine_cost numeric DEFAULT 0 NOT NULL,\n  prebowled_on date\n);
CREATE TABLE IF NOT EXISTS public.shots (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid NOT NULL,\n  team_id uuid,\n  league_id uuid,\n  date date NOT NULL,\n  game integer NOT NULL,\n  frame integer NOT NULL,\n  ball_num integer,\n  lane text,\n  ball text,\n  surface text,\n  starting_board text,\n  target_arrows text,\n  result text NOT NULL,\n  other_leave jsonb DEFAULT '[]'::jsonb NOT NULL,\n  spare_made text DEFAULT ''::text NOT NULL,\n  strike_description text DEFAULT ''::text NOT NULL,\n  release text DEFAULT ''::text NOT NULL,\n  miss jsonb DEFAULT '[]'::jsonb NOT NULL,\n  ball_change_reason jsonb DEFAULT '[]'::jsonb NOT NULL,\n  pin_count text DEFAULT ''::text NOT NULL,\n  notes text DEFAULT ''::text NOT NULL,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  bowler_name text DEFAULT ''::text NOT NULL,\n  display_result text DEFAULT ''::text NOT NULL,\n  display_leave jsonb DEFAULT '[]'::jsonb NOT NULL,\n  ball_speed numeric,\n  actual_board numeric,\n  actual_arrows numeric,\n  heel_number text,\n  sole_number text,\n  rev_rate numeric,\n  axis_rotation numeric,\n  imported_from uuid\n);
CREATE TABLE IF NOT EXISTS public.sync_tombstones (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  table_name text NOT NULL,\n  row_id uuid NOT NULL,\n  user_id uuid NOT NULL,\n  deleted_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.team_members (\n  team_id uuid NOT NULL,\n  user_id uuid NOT NULL,\n  lineup_position integer,\n  joined_at timestamp with time zone DEFAULT now() NOT NULL,\n  left_handed boolean DEFAULT false NOT NULL,\n  is_sub boolean DEFAULT false NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.teams (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  name text NOT NULL,\n  league_id uuid NOT NULL,\n  created_by uuid DEFAULT auth.uid(),\n  created_at timestamp with time zone DEFAULT now() NOT NULL\n);
CREATE TABLE IF NOT EXISTS public.tournaments (\n  id uuid DEFAULT gen_random_uuid() NOT NULL,\n  user_id uuid,\n  bowler_name text NOT NULL,\n  name text NOT NULL,\n  center text,\n  days jsonb DEFAULT '[]'::jsonb NOT NULL,\n  buy_in numeric,\n  winnings numeric,\n  notes text,\n  created_at timestamp with time zone DEFAULT now() NOT NULL,\n  updated_at timestamp with time zone DEFAULT now() NOT NULL,\n  side_pots jsonb DEFAULT '[]'::jsonb NOT NULL,\n  match_play jsonb DEFAULT '{}'::jsonb NOT NULL,\n  placement text,\n  placement_note text\n);
CREATE TABLE IF NOT EXISTS public.user_preferences (\n  user_id uuid NOT NULL,\n  preferences jsonb DEFAULT '{}'::jsonb NOT NULL,\n  updated_at timestamp with time zone DEFAULT now()\n);
ALTER TABLE public.api_usage ADD CONSTRAINT api_usage_pkey PRIMARY KEY (id);
ALTER TABLE public.api_usage ADD CONSTRAINT api_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.arsenals ADD CONSTRAINT arsenal_pkey PRIMARY KEY (id);
ALTER TABLE public.arsenals ADD CONSTRAINT arsenals_core_type_check CHECK (((core_type IS NULL) OR (core_type = ANY (ARRAY['symmetric'::text, 'asymmetric'::text]))));
ALTER TABLE public.arsenals ADD CONSTRAINT arsenals_coverstock_check CHECK (((coverstock IS NULL) OR (coverstock = ANY (ARRAY['solid'::text, 'pearl'::text, 'hybrid'::text]))));
ALTER TABLE public.arsenals ADD CONSTRAINT arsenals_layout_system_check CHECK (((layout_system IS NULL) OR (layout_system = ANY (ARRAY['dual_angle'::text, 'vls'::text, '2ls'::text]))));
ALTER TABLE public.arsenals ADD CONSTRAINT arsenals_group_id_fkey FOREIGN KEY (group_id) REFERENCES ball_groups(id) ON DELETE SET NULL;
ALTER TABLE public.bags ADD CONSTRAINT bags_pkey PRIMARY KEY (id);
ALTER TABLE public.bags ADD CONSTRAINT bags_created_by_bowler_name_name_key UNIQUE (created_by, bowler_name, name);
ALTER TABLE public.bags ADD CONSTRAINT bags_bag_type_check CHECK ((bag_type = ANY (ARRAY['league'::text, 'tournament'::text])));
ALTER TABLE public.bags ADD CONSTRAINT bags_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ball_bags ADD CONSTRAINT ball_bags_pkey PRIMARY KEY (id);
ALTER TABLE public.ball_bags ADD CONSTRAINT ball_bags_created_by_bowler_name_ball_bag_id_key UNIQUE (created_by, bowler_name, ball, bag_id);
ALTER TABLE public.ball_bags ADD CONSTRAINT ball_bags_bag_id_fkey FOREIGN KEY (bag_id) REFERENCES bags(id) ON DELETE CASCADE;
ALTER TABLE public.ball_bags ADD CONSTRAINT ball_bags_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ball_confirmations ADD CONSTRAINT ball_confirmations_pkey PRIMARY KEY (id);
ALTER TABLE public.ball_confirmations ADD CONSTRAINT ball_confirmations_submission_id_confirmed_by_key UNIQUE (submission_id, confirmed_by);
ALTER TABLE public.ball_confirmations ADD CONSTRAINT ball_confirmations_vote_check CHECK ((vote = ANY (ARRAY['approve'::text, 'reject'::text])));
ALTER TABLE public.ball_confirmations ADD CONSTRAINT ball_confirmations_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ball_confirmations ADD CONSTRAINT ball_confirmations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES ball_submissions(id) ON DELETE CASCADE;
ALTER TABLE public.ball_groups ADD CONSTRAINT ball_groups_pkey PRIMARY KEY (id);
ALTER TABLE public.ball_groups ADD CONSTRAINT ball_groups_created_by_bowler_name_name_key UNIQUE (created_by, bowler_name, name);
ALTER TABLE public.ball_groups ADD CONSTRAINT ball_groups_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ball_submissions ADD CONSTRAINT ball_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.ball_submissions ADD CONSTRAINT ball_submissions_submitted_by_ball_key_key UNIQUE (submitted_by, ball_key);
ALTER TABLE public.ball_submissions ADD CONSTRAINT ball_submissions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.bowler_goals ADD CONSTRAINT bowler_goals_pkey PRIMARY KEY (id);
ALTER TABLE public.bowler_goals ADD CONSTRAINT bowler_goals_created_by_bowler_name_key UNIQUE (created_by, bowler_name);
ALTER TABLE public.bowler_goals ADD CONSTRAINT bowler_goals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.bowler_names ADD CONSTRAINT bowler_names_pkey PRIMARY KEY (id);
ALTER TABLE public.bowler_profiles ADD CONSTRAINT bowler_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.bowler_profiles ADD CONSTRAINT bowler_profiles_created_by_bowler_name_key UNIQUE (created_by, bowler_name);
ALTER TABLE public.bowler_profiles ADD CONSTRAINT bowler_profiles_owner_name_key UNIQUE (created_by, bowler_name);
ALTER TABLE public.bowler_profiles ADD CONSTRAINT bowler_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.bowling_centers ADD CONSTRAINT bowling_centers_pkey PRIMARY KEY (id);
ALTER TABLE public.bowling_centers ADD CONSTRAINT bowling_centers_here_id_key UNIQUE (here_id);
ALTER TABLE public.bowling_centers ADD CONSTRAINT bowling_centers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.coaching_notes ADD CONSTRAINT coaching_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.coaching_notes ADD CONSTRAINT coaching_notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_notes ADD CONSTRAINT coaching_notes_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES coaching_relationships(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_pkey PRIMARY KEY (id);
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_coach_id_bowler_id_key UNIQUE (coach_id, bowler_id);
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_check CHECK ((coach_id <> bowler_id));
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])));
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_bowler_id_fkey FOREIGN KEY (bowler_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_relationships ADD CONSTRAINT coaching_relationships_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_tasks ADD CONSTRAINT coaching_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.coaching_tasks ADD CONSTRAINT coaching_tasks_status_check CHECK ((status = ANY (ARRAY['open'::text, 'completed'::text, 'attempted'::text])));
ALTER TABLE public.coaching_tasks ADD CONSTRAINT coaching_tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.coaching_tasks ADD CONSTRAINT coaching_tasks_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES coaching_relationships(id) ON DELETE CASCADE;
ALTER TABLE public.drills ADD CONSTRAINT drills_pkey PRIMARY KEY (id);
ALTER TABLE public.drills ADD CONSTRAINT drills_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.friendships ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);
ALTER TABLE public.friendships ADD CONSTRAINT friendships_requester_id_addressee_id_key UNIQUE (requester_id, addressee_id);
ALTER TABLE public.friendships ADD CONSTRAINT friendships_check CHECK ((requester_id <> addressee_id));
ALTER TABLE public.friendships ADD CONSTRAINT friendships_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])));
ALTER TABLE public.friendships ADD CONSTRAINT friendships_addressee_id_fkey FOREIGN KEY (addressee_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.friendships ADD CONSTRAINT friendships_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.hidden_leagues ADD CONSTRAINT hidden_leagues_pkey PRIMARY KEY (id);
ALTER TABLE public.hidden_leagues ADD CONSTRAINT hidden_leagues_user_id_league_id_key UNIQUE (user_id, league_id);
ALTER TABLE public.hidden_leagues ADD CONSTRAINT hidden_leagues_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
ALTER TABLE public.hidden_leagues ADD CONSTRAINT hidden_leagues_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.imported_scores ADD CONSTRAINT imported_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.imported_scores ADD CONSTRAINT imported_scores_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'verified'::text, 'corrected'::text, 'rejected'::text])));
ALTER TABLE public.imported_scores ADD CONSTRAINT imported_scores_bowler_user_id_fkey FOREIGN KEY (bowler_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.imported_scores ADD CONSTRAINT imported_scores_corrected_by_fkey FOREIGN KEY (corrected_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.imported_scores ADD CONSTRAINT imported_scores_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.lane_patterns ADD CONSTRAINT lane_patterns_pkey PRIMARY KEY (id);
ALTER TABLE public.lane_patterns ADD CONSTRAINT lane_patterns_team_id_date_lane_key UNIQUE (team_id, date, lane);
ALTER TABLE public.lane_patterns ADD CONSTRAINT lane_patterns_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE SET NULL;
ALTER TABLE public.lane_patterns ADD CONSTRAINT lane_patterns_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.leagues ADD CONSTRAINT leagues_pkey PRIMARY KEY (id);
ALTER TABLE public.leagues ADD CONSTRAINT leagues_center_id_fkey FOREIGN KEY (center_id) REFERENCES bowling_centers(id) ON DELETE SET NULL;
ALTER TABLE public.leagues ADD CONSTRAINT leagues_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.manual_scores ADD CONSTRAINT manual_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.manual_scores ADD CONSTRAINT manual_scores_slot_key UNIQUE (user_id, bowler_name, league_id, date, game);
ALTER TABLE public.manual_scores ADD CONSTRAINT manual_scores_user_id_bowler_name_league_id_date_game_key UNIQUE (user_id, bowler_name, league_id, date, game);
ALTER TABLE public.manual_scores ADD CONSTRAINT manual_scores_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
ALTER TABLE public.manual_scores ADD CONSTRAINT manual_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.matches ADD CONSTRAINT matches_pkey PRIMARY KEY (id);
ALTER TABLE public.matches ADD CONSTRAINT matches_team_id_date_key UNIQUE (team_id, date);
ALTER TABLE public.matches ADD CONSTRAINT matches_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE SET NULL;
ALTER TABLE public.matches ADD CONSTRAINT matches_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.oil_patterns ADD CONSTRAINT oil_patterns_pkey PRIMARY KEY (id);
ALTER TABLE public.oil_patterns ADD CONSTRAINT oil_patterns_name_key UNIQUE (name);
ALTER TABLE public.oil_patterns ADD CONSTRAINT oil_patterns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.pending_invites ADD CONSTRAINT pending_invites_pkey PRIMARY KEY (id);
ALTER TABLE public.pending_invites ADD CONSTRAINT pending_invites_team_id_invited_email_key UNIQUE (team_id, invited_email);
ALTER TABLE public.pending_invites ADD CONSTRAINT pending_invites_accepted_user_id_fkey FOREIGN KEY (accepted_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.pending_invites ADD CONSTRAINT pending_invites_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.pending_invites ADD CONSTRAINT pending_invites_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_user_id_bowler_name_league_id_date_key UNIQUE (user_id, bowler_name, league_id, date);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.shots ADD CONSTRAINT shots_pkey PRIMARY KEY (id);
ALTER TABLE public.shots ADD CONSTRAINT shots_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE SET NULL;
ALTER TABLE public.shots ADD CONSTRAINT shots_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.shots ADD CONSTRAINT shots_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.sync_tombstones ADD CONSTRAINT sync_tombstones_pkey PRIMARY KEY (id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_pkey PRIMARY KEY (team_id, user_id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_members ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.teams ADD CONSTRAINT teams_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_pkey PRIMARY KEY (id);
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX api_usage_lookup_idx ON public.api_usage USING btree (user_id, endpoint, called_at DESC);
CREATE INDEX bags_lookup_idx ON public.bags USING btree (created_by, bowler_name);
CREATE INDEX ball_bags_lookup_idx ON public.ball_bags USING btree (created_by, bowler_name);
CREATE INDEX ball_confirmations_submission_idx ON public.ball_confirmations USING btree (submission_id);
CREATE INDEX ball_groups_lookup_idx ON public.ball_groups USING btree (created_by, bowler_name);
CREATE INDEX ball_submissions_key_idx ON public.ball_submissions USING btree (ball_key);
CREATE UNIQUE INDEX ball_submissions_official_key_idx ON public.ball_submissions USING btree (ball_key) WHERE (official = true);
CREATE INDEX bowling_centers_name_idx ON public.bowling_centers USING btree (lower(name));
CREATE INDEX coaching_notes_relationship_idx ON public.coaching_notes USING btree (relationship_id);
CREATE INDEX coaching_tasks_relationship_idx ON public.coaching_tasks USING btree (relationship_id);
CREATE INDEX drills_lookup_idx ON public.drills USING btree (user_id, bowler_name, target);
CREATE INDEX friendships_addressee_idx ON public.friendships USING btree (addressee_id);
CREATE INDEX friendships_requester_idx ON public.friendships USING btree (requester_id);
CREATE INDEX hidden_leagues_user_idx ON public.hidden_leagues USING btree (user_id);
CREATE INDEX imported_scores_bowler_idx ON public.imported_scores USING btree (bowler_user_id);
CREATE INDEX imported_scores_team_idx ON public.imported_scores USING btree (team_id, date);
CREATE INDEX lane_patterns_league_id_idx ON public.lane_patterns USING btree (league_id);
CREATE INDEX lane_patterns_team_id_idx ON public.lane_patterns USING btree (team_id);
CREATE UNIQUE INDEX leagues_name_per_user_idx ON public.leagues USING btree (created_by, name);
CREATE INDEX manual_scores_lookup_idx ON public.manual_scores USING btree (user_id, bowler_name, date);
CREATE INDEX matches_league_id_idx ON public.matches USING btree (league_id);
CREATE INDEX matches_team_id_idx ON public.matches USING btree (team_id);
CREATE INDEX oil_patterns_name_idx ON public.oil_patterns USING btree (lower(name));
CREATE INDEX pending_invites_email_idx ON public.pending_invites USING btree (invited_email);
CREATE UNIQUE INDEX pending_invites_signup_code_open_idx ON public.pending_invites USING btree (signup_code) WHERE ((signup_code IS NOT NULL) AND (accepted_at IS NULL));
CREATE INDEX pending_invites_team_id_idx ON public.pending_invites USING btree (team_id);
CREATE INDEX sessions_bowler_name_idx ON public.sessions USING btree (bowler_name);
CREATE UNIQUE INDEX sessions_no_league_uniq ON public.sessions USING btree (user_id, bowler_name, date) WHERE (league_id IS NULL);
CREATE INDEX sessions_team_id_idx ON public.sessions USING btree (team_id);
CREATE INDEX sessions_user_id_idx ON public.sessions USING btree (user_id);
CREATE INDEX sessions_user_updated_idx ON public.sessions USING btree (user_id, updated_at);
CREATE INDEX shots_bowler_name_idx ON public.shots USING btree (bowler_name);
CREATE UNIQUE INDEX shots_identity_uniq ON public.shots USING btree (user_id, bowler_name, COALESCE(league_id, '00000000-0000-0000-0000-000000000000'::uuid), date, game, frame, COALESCE(ball_num, 1));
CREATE INDEX shots_team_id_idx ON public.shots USING btree (team_id);
CREATE INDEX shots_user_date_idx ON public.shots USING btree (user_id, date);
CREATE INDEX shots_user_id_idx ON public.shots USING btree (user_id);
CREATE INDEX shots_user_updated_idx ON public.shots USING btree (user_id, updated_at);
CREATE INDEX sync_tombstones_lookup_idx ON public.sync_tombstones USING btree (table_name, user_id, deleted_at);
CREATE INDEX team_members_user_id_idx ON public.team_members USING btree (user_id);
CREATE INDEX teams_league_id_idx ON public.teams USING btree (league_id);
CREATE INDEX tournaments_user_bowler_idx ON public.tournaments USING btree (user_id, bowler_name);
ALTER TABLE public.api_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arsenals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ball_bags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ball_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ball_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ball_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bowler_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bowler_names ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bowler_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bowling_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaching_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaching_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaching_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hidden_leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.imported_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lane_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oil_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_tombstones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY 'teammates can view each other''s arsenal entries' ON public.arsenals FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = arsenals.created_by)))));
CREATE POLICY 'users can add their own arsenal entries' ON public.arsenals FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can remove their own arsenal entries' ON public.arsenals FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can update their own arsenal entries' ON public.arsenals FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own arsenal entries' ON public.arsenals FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s bags' ON public.bags FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = bags.created_by)))));
CREATE POLICY 'users can delete their own bags' ON public.bags FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can insert their own bags' ON public.bags FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can update their own bags' ON public.bags FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own bags' ON public.bags FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s ball bag assignments' ON public.ball_bags FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = ball_bags.created_by)))));
CREATE POLICY 'users can delete their own ball bag assignments' ON public.ball_bags FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can insert their own ball bag assignments' ON public.ball_bags FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can update their own ball bag assignments' ON public.ball_bags FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own ball bag assignments' ON public.ball_bags FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'anyone can read confirmations' ON public.ball_confirmations FOR SELECT TO authenticated\n  USING ((auth.uid() IS NOT NULL));
CREATE POLICY 'users can change their own vote' ON public.ball_confirmations FOR UPDATE TO authenticated\n  USING ((confirmed_by = auth.uid()))\n  WITH CHECK ((confirmed_by = auth.uid()));
CREATE POLICY 'users can confirm as themselves' ON public.ball_confirmations FOR INSERT TO authenticated\n  WITH CHECK ((confirmed_by = auth.uid()));
CREATE POLICY 'users can withdraw their own confirmation' ON public.ball_confirmations FOR DELETE TO authenticated\n  USING ((confirmed_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s ball groups' ON public.ball_groups FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = ball_groups.created_by)))));
CREATE POLICY 'users can delete their own ball groups' ON public.ball_groups FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can insert their own ball groups' ON public.ball_groups FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can update their own ball groups' ON public.ball_groups FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own ball groups' ON public.ball_groups FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'anyone can read ball submissions' ON public.ball_submissions FOR SELECT TO authenticated\n  USING ((auth.uid() IS NOT NULL));
CREATE POLICY 'users can delete only their own submission' ON public.ball_submissions FOR DELETE TO authenticated\n  USING ((submitted_by = auth.uid()));
CREATE POLICY 'users can insert their own submission' ON public.ball_submissions FOR INSERT TO authenticated\n  WITH CHECK ((submitted_by = auth.uid()));
CREATE POLICY 'users can update only their own submission' ON public.ball_submissions FOR UPDATE TO authenticated\n  USING ((submitted_by = auth.uid()))\n  WITH CHECK ((submitted_by = auth.uid()));
CREATE POLICY 'users can delete their own bowler goals' ON public.bowler_goals FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can insert their own bowler goals' ON public.bowler_goals FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can update their own bowler goals' ON public.bowler_goals FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own bowler goals' ON public.bowler_goals FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s bowler names' ON public.bowler_names FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = bowler_names.created_by)))));
CREATE POLICY 'users can add their own bowler names' ON public.bowler_names FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can remove their own bowler names' ON public.bowler_names FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can update their own bowler names' ON public.bowler_names FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own bowler names' ON public.bowler_names FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can delete their own bowler profiles' ON public.bowler_profiles FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'users can insert their own bowler profiles' ON public.bowler_profiles FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can update their own bowler profiles' ON public.bowler_profiles FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'users can view their own bowler profiles' ON public.bowler_profiles FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'anyone can read bowling centers' ON public.bowling_centers FOR SELECT TO authenticated\n  USING ((auth.uid() IS NOT NULL));
CREATE POLICY 'creators can correct their own hand-entered centers' ON public.bowling_centers FOR UPDATE TO authenticated\n  USING (((created_by = auth.uid()) AND (here_id IS NULL)))\n  WITH CHECK (((created_by = auth.uid()) AND (here_id IS NULL)));
CREATE POLICY 'signed-in users can add centers' ON public.bowling_centers FOR INSERT TO authenticated\n  WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY 'authors can delete their own notes' ON public.coaching_notes FOR DELETE TO authenticated\n  USING ((author_id = auth.uid()));
CREATE POLICY 'authors can edit their own notes' ON public.coaching_notes FOR UPDATE TO authenticated\n  USING ((author_id = auth.uid()))\n  WITH CHECK ((author_id = auth.uid()));
CREATE POLICY 'both sides can view notes' ON public.coaching_notes FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_notes.relationship_id) AND (r.status = 'accepted'::text) AND ((r.coach_id = auth.uid()) OR (r.bowler_id = auth.uid()))))));
CREATE POLICY 'both sides can write notes' ON public.coaching_notes FOR INSERT TO authenticated\n  WITH CHECK (((author_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_notes.relationship_id) AND (r.status = 'accepted'::text) AND ((r.coach_id = auth.uid()) OR (r.bowler_id = auth.uid())))))));
CREATE POLICY 'either side can end a coaching relationship' ON public.coaching_relationships FOR DELETE TO authenticated\n  USING (((coach_id = auth.uid()) OR (bowler_id = auth.uid())));
CREATE POLICY 'either side can update their coaching relationship' ON public.coaching_relationships FOR UPDATE TO authenticated\n  USING (((coach_id = auth.uid()) OR (bowler_id = auth.uid())))\n  WITH CHECK (((coach_id = auth.uid()) OR (bowler_id = auth.uid())));
CREATE POLICY 'either side can view their coaching relationship' ON public.coaching_relationships FOR SELECT TO authenticated\n  USING (((coach_id = auth.uid()) OR (bowler_id = auth.uid())));
CREATE POLICY 'users can request a coaching relationship' ON public.coaching_relationships FOR INSERT TO authenticated\n  WITH CHECK (((requested_by = auth.uid()) AND ((coach_id = auth.uid()) OR (bowler_id = auth.uid()))));
CREATE POLICY 'both sides can update tasks' ON public.coaching_tasks FOR UPDATE TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_tasks.relationship_id) AND (r.status = 'accepted'::text) AND ((r.coach_id = auth.uid()) OR (r.bowler_id = auth.uid()))))))\n  WITH CHECK ((EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_tasks.relationship_id) AND (r.status = 'accepted'::text) AND ((r.coach_id = auth.uid()) OR (r.bowler_id = auth.uid()))))));
CREATE POLICY 'both sides can view tasks' ON public.coaching_tasks FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_tasks.relationship_id) AND (r.status = 'accepted'::text) AND ((r.coach_id = auth.uid()) OR (r.bowler_id = auth.uid()))))));
CREATE POLICY 'the coach can assign tasks' ON public.coaching_tasks FOR INSERT TO authenticated\n  WITH CHECK (((assigned_by = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_tasks.relationship_id) AND (r.status = 'accepted'::text) AND (r.coach_id = auth.uid()))))));
CREATE POLICY 'the coach can remove tasks' ON public.coaching_tasks FOR DELETE TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM coaching_relationships r\n  WHERE ((r.id = coaching_tasks.relationship_id) AND (r.status = 'accepted'::text) AND (r.coach_id = auth.uid())))));
CREATE POLICY 'users manage their own drills' ON public.drills FOR ALL TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'either side can delete a friendship' ON public.friendships FOR DELETE TO authenticated\n  USING (((requester_id = auth.uid()) OR (addressee_id = auth.uid())));
CREATE POLICY 'either side can respond to or cancel a request' ON public.friendships FOR UPDATE TO authenticated\n  USING (((requester_id = auth.uid()) OR (addressee_id = auth.uid())))\n  WITH CHECK (((requester_id = auth.uid()) OR (addressee_id = auth.uid())));
CREATE POLICY 'users can send friend requests' ON public.friendships FOR INSERT TO authenticated\n  WITH CHECK ((requester_id = auth.uid()));
CREATE POLICY 'users can view friendships they''re part of' ON public.friendships FOR SELECT TO authenticated\n  USING (((requester_id = auth.uid()) OR (addressee_id = auth.uid())));
CREATE POLICY 'users can hide leagues for themselves' ON public.hidden_leagues FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can unhide their own leagues' ON public.hidden_leagues FOR DELETE TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can update their own hidden leagues' ON public.hidden_leagues FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own hidden leagues' ON public.hidden_leagues FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'bowler or team can update imported scores' ON public.imported_scores FOR UPDATE TO authenticated\n  USING (((bowler_user_id = auth.uid()) OR ((team_id IS NOT NULL) AND is_team_member(team_id))));
CREATE POLICY 'team can view imported scores' ON public.imported_scores FOR SELECT TO authenticated\n  USING (((bowler_user_id = auth.uid()) OR (uploaded_by = auth.uid()) OR ((team_id IS NOT NULL) AND is_team_member(team_id))));
CREATE POLICY 'teammates can upload scores' ON public.imported_scores FOR INSERT TO authenticated\n  WITH CHECK (((uploaded_by = auth.uid()) AND ((team_id IS NULL) OR is_team_member(team_id))));
CREATE POLICY 'uploader can delete their upload' ON public.imported_scores FOR DELETE TO authenticated\n  USING ((uploaded_by = auth.uid()));
CREATE POLICY 'team members can delete their team''s lane patterns' ON public.lane_patterns FOR DELETE TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can log lane patterns for their team' ON public.lane_patterns FOR INSERT TO authenticated\n  WITH CHECK (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can update their team''s lane patterns' ON public.lane_patterns FOR UPDATE TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)))\n  WITH CHECK (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can view their team''s lane patterns' ON public.lane_patterns FOR SELECT TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'league members or its creator can update it' ON public.leagues FOR UPDATE TO authenticated\n  USING ((is_league_member(id) OR (created_by = auth.uid())))\n  WITH CHECK ((is_league_member(id) OR (created_by = auth.uid())));
CREATE POLICY 'leagues are viewable by any authenticated user' ON public.leagues FOR SELECT TO authenticated\n  USING (true);
CREATE POLICY 'users can create leagues as themselves' ON public.leagues FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s manual scores' ON public.manual_scores FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = manual_scores.user_id)))));
CREATE POLICY 'users can delete their own manual scores' ON public.manual_scores FOR DELETE TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can insert their own manual scores' ON public.manual_scores FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can update their own manual scores' ON public.manual_scores FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own manual scores' ON public.manual_scores FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'team members can delete their team''s matches' ON public.matches FOR DELETE TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can log matches for their team' ON public.matches FOR INSERT TO authenticated\n  WITH CHECK (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can update their team''s matches' ON public.matches FOR UPDATE TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)))\n  WITH CHECK (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'team members can view their team''s matches' ON public.matches FOR SELECT TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'anyone can read oil patterns' ON public.oil_patterns FOR SELECT TO authenticated\n  USING ((auth.uid() IS NOT NULL));
CREATE POLICY 'creators can correct their own unverified patterns' ON public.oil_patterns FOR UPDATE TO authenticated\n  USING (((created_by = auth.uid()) AND (verified = false)))\n  WITH CHECK (((created_by = auth.uid()) AND (verified = false)));
CREATE POLICY 'signed-in users can add patterns' ON public.oil_patterns FOR INSERT TO authenticated\n  WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY 'invitees can answer their own invites' ON public.pending_invites FOR UPDATE TO authenticated\n  USING ((lower(invited_email) = lower((auth.jwt() ->> 'email'::text))))\n  WITH CHECK ((lower(invited_email) = lower((auth.jwt() ->> 'email'::text))));
CREATE POLICY 'invitees can view their own invites' ON public.pending_invites FOR SELECT TO authenticated\n  USING ((lower(invited_email) = lower((auth.jwt() ->> 'email'::text))));
CREATE POLICY 'team members can create invites for their teams' ON public.pending_invites FOR INSERT TO authenticated\n  WITH CHECK (is_team_member(team_id));
CREATE POLICY 'team members can delete pending invites for their teams' ON public.pending_invites FOR DELETE TO authenticated\n  USING (is_team_member(team_id));
CREATE POLICY 'team members can manually link a placeholder to any account' ON public.pending_invites FOR UPDATE TO authenticated\n  USING ((is_team_member(team_id) AND (accepted_at IS NULL)))\n  WITH CHECK (is_team_member(team_id));
CREATE POLICY 'team members can view pending invites for their teams' ON public.pending_invites FOR SELECT TO authenticated\n  USING (is_team_member(team_id));
CREATE POLICY 'users can claim invites addressed to their own email' ON public.pending_invites FOR UPDATE TO authenticated\n  USING (((accepted_at IS NULL) AND (invited_email = (auth.jwt() ->> 'email'::text))))\n  WITH CHECK ((accepted_user_id = auth.uid()));
CREATE POLICY 'users can view invites addressed to their own email' ON public.pending_invites FOR SELECT TO authenticated\n  USING (((accepted_at IS NULL) AND (invited_email = (auth.jwt() ->> 'email'::text))));
CREATE POLICY 'profiles are viewable by any authenticated user' ON public.profiles FOR SELECT TO authenticated\n  USING (true);
CREATE POLICY 'users can insert their own profile' ON public.profiles FOR INSERT TO authenticated\n  WITH CHECK ((id = auth.uid()));
CREATE POLICY 'users can update their own profile' ON public.profiles FOR UPDATE TO authenticated\n  USING ((id = auth.uid()))\n  WITH CHECK ((id = auth.uid()));
CREATE POLICY 'coaches can view their bowler''s sessions' ON public.sessions FOR SELECT TO authenticated\n  USING (is_accepted_coach_of(user_id));
CREATE POLICY 'friends can view each other''s sessions' ON public.sessions FOR SELECT TO authenticated\n  USING (are_friends(user_id));
CREATE POLICY 'teammates can view each other''s sessions' ON public.sessions FOR SELECT TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'users can delete their own sessions' ON public.sessions FOR DELETE TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can insert their own sessions' ON public.sessions FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can update their own sessions' ON public.sessions FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own sessions' ON public.sessions FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'coaches can view their bowler''s shots' ON public.shots FOR SELECT TO authenticated\n  USING (is_accepted_coach_of(user_id));
CREATE POLICY 'friends can view each other''s shots' ON public.shots FOR SELECT TO authenticated\n  USING (are_friends(user_id));
CREATE POLICY 'teammates can view each other''s shots' ON public.shots FOR SELECT TO authenticated\n  USING (((team_id IS NOT NULL) AND is_team_member(team_id)));
CREATE POLICY 'users can delete their own shots' ON public.shots FOR DELETE TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can insert their own shots' ON public.shots FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can update their own shots' ON public.shots FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own shots' ON public.shots FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'user can read their own tombstones' ON public.sync_tombstones FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'team members can remove roster entries' ON public.team_members FOR DELETE TO authenticated\n  USING (is_team_member(team_id));
CREATE POLICY 'team members can reorder their team''s roster' ON public.team_members FOR UPDATE TO authenticated\n  USING (is_team_member(team_id))\n  WITH CHECK (is_team_member(team_id));
CREATE POLICY 'team members can view their own roster' ON public.team_members FOR SELECT TO authenticated\n  USING (is_team_member(team_id));
CREATE POLICY 'you can only add yourself to a roster' ON public.team_members FOR INSERT TO authenticated\n  WITH CHECK (((user_id = auth.uid()) AND ((EXISTS ( SELECT 1\n   FROM teams\n  WHERE ((teams.id = team_members.team_id) AND (teams.created_by = auth.uid())))) OR (EXISTS ( SELECT 1\n   FROM pending_invites\n  WHERE ((pending_invites.team_id = team_members.team_id) AND (lower(pending_invites.invited_email) = lower((auth.jwt() ->> 'email'::text))) AND (pending_invites.accepted_at IS NULL)))))));
CREATE POLICY 'team creators can delete their team' ON public.teams FOR DELETE TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'team creators can rename their team' ON public.teams FOR UPDATE TO authenticated\n  USING ((created_by = auth.uid()))\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'team creators can view their team' ON public.teams FOR SELECT TO authenticated\n  USING ((created_by = auth.uid()));
CREATE POLICY 'team members can delete their team' ON public.teams FOR DELETE TO authenticated\n  USING (is_team_member(id));
CREATE POLICY 'team members can rename their team' ON public.teams FOR UPDATE TO authenticated\n  USING (is_team_member(id))\n  WITH CHECK (is_team_member(id));
CREATE POLICY 'team members can view their team' ON public.teams FOR SELECT TO authenticated\n  USING (is_team_member(id));
CREATE POLICY 'users can create teams as themselves' ON public.teams FOR INSERT TO authenticated\n  WITH CHECK ((created_by = auth.uid()));
CREATE POLICY 'teammates can view each other''s tournaments' ON public.tournaments FOR SELECT TO authenticated\n  USING ((EXISTS ( SELECT 1\n   FROM (team_members me\n     JOIN team_members them ON ((them.team_id = me.team_id)))\n  WHERE ((me.user_id = auth.uid()) AND (them.user_id = tournaments.user_id)))));
CREATE POLICY 'users can delete their own tournaments' ON public.tournaments FOR DELETE TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can insert their own tournaments' ON public.tournaments FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can update their own tournaments' ON public.tournaments FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own tournaments' ON public.tournaments FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE POLICY 'users can insert their own preferences' ON public.user_preferences FOR INSERT TO authenticated\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can update their own preferences' ON public.user_preferences FOR UPDATE TO authenticated\n  USING ((user_id = auth.uid()))\n  WITH CHECK ((user_id = auth.uid()));
CREATE POLICY 'users can view their own preferences' ON public.user_preferences FOR SELECT TO authenticated\n  USING ((user_id = auth.uid()));
CREATE TRIGGER sessions_record_tombstone AFTER DELETE ON public.sessions FOR EACH ROW EXECUTE FUNCTION record_tombstone();
CREATE TRIGGER sessions_set_updated_at BEFORE UPDATE ON public.sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER shots_record_tombstone AFTER DELETE ON public.shots FOR EACH ROW EXECUTE FUNCTION record_tombstone();
CREATE TRIGGER shots_set_updated_at BEFORE UPDATE ON public.shots FOR EACH ROW EXECUTE FUNCTION set_updated_at();
